### ISSUE TITLE
Epic: Run 1.1: Re-run DM workflow on Run 1 images

### ISSUE THREAD

**Issue by tony-johnson** [DarkEnergyScienceCollaboration/Twinkles#187]
The pre-requisites are to fix:
- [x] Division by zero problem #161 
- [x] "Number of columns of design matrix (6) must be smaller than number of data points (0)" #162 
- [x] Stale file handle when running at scale at SLAC #163 
- [x] Cross-filter astrometric registration #175 
- [x] ISR to cope with saturated stars #94

When all these are done:
- [x] Re-run DM workflow #206

**Comment by drphilmarshall** [comment]
I think you are pretty close to finishing this epic, Tony :-)

**Comment by tony-johnson** [comment]
Yes, we are close, but we still have to try out the fixes for #161 and #162 (I need to clarify with @SimonKrughoff and @jchiang87 whether the fixes are currently available in DM builds at SLAC, see #223)

**Comment by jchiang87** [comment]
The fixes for #161 and #162 are in the LSST_Stack_2016-04-12 installation, but I guess we should wait for the DM-4302 branch to be merged into master (then rebuild obs_lsstSim) before trying again.

**Comment by tony-johnson** [comment]
This is done.

**Comment by drphilmarshall** [comment]
Rock. On.

Here's the final burndown chart:

![image](https://cloud.githubusercontent.com/assets/710903/14905867/1020b506-0d6a-11e6-9269-9f29db5af089.png)

I think it must be plotting issues by their *start date* not their finish date, which is interesting. It makes it look as though we released Run 1.1 a week early! Oh well :-)
