### ISSUE TITLE
Set up world-accessible database to serve up Twinkles Level 2 data

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#191]
Let's see, what needs to be done to complete this epic task? (Now renamed to better represent its epic nature.)

* [x] Implement and test a simple MySQL version of the database we want to see. PR in #184
* [x] Explore and discuss various options for database type (dbserve? qserv? sqlite? pandas?!) and location (SLAC? NERSC?). Recommend solutions for Run 1, Run 2, and Twinkles 1. See discussion in #195 , and then #216 for the actual work
* [x] Implement Run 1 database solution

**Comment by drphilmarshall** [comment]
Great! :-) Can you post the link to the doc that explains how to do this,
please? Thanks!

**Comment by jchiang87** [comment]
That's something that's being worked on in the Monitor package at [issue 24](https://github.com/DarkEnergyScienceCollaboration/Monitor/pull/26).  I don't actually know how to set up the ssh tunnel to get outside-of-NERSC access, but @jbkalmbach does.  I'm hoping that once the implementation issues are settled, we can document access over there.

**Comment by drphilmarshall** [comment]
Sounds good: we can just put a few links from the Twinkles docs. Thanks!
