### ISSUE TITLE
Issue tending

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#193]
While all you @DarkEnergyScienceCollaboration/twinkles people tend your own issues (click on your avatar to filter the list), I will wrangle the whole lot to make sure everything is assigned and labeled. Please close issues aggressively - we can always re-open them if we disagree!

Notes to self from chatting with @tony-johnson and @jbkalmbach: 

* [x] Re-assign issues to Run 2 milestones, and while doing so, think about any nearer milestones that could be of use
* [x] Look for groups of issues that could be assigned to an Epic. The NERSC test is one example, there are bound to be others.
* [ ] Look up ZenHub "Story Points" and adopt some system for estimating "complexity", so as to enable the use of Burndown Charts - these look useful for trying to ensure progress happens *linearly*
* [x] Try labelling by: Goal (of which we have multiple), Criticality, Opportunity ("help wanted") - and move to color scheme that brings these things out. Labels are good for 2 things: filtering the issue list, and improving visual parsing of both the list and the ZenHub board.
* [x] Clean up the watchlist, by asking old owners if they want to be removed. 

This is on top of the initial tasks:

* [x] Make sure all issues are assigned, labelled, and milestoned
* [x] Make sure all assignees are up to date with their issue monitoring

**Comment by drphilmarshall** [comment]
Notes to self from chatting with @tony-johnson and @jbkalmbach: 

* [ ] Re-assign issues to Run 2 milestones, and while doing so, think about any nearer milestones that could be of use
* [ ] Look for groups of issues that could be assigned to an Epic. The NERSC test is one example, there are bound to be others.
* [ ] Look up ZenHub "Story Points" and adopt some system for estimating "complexity", so as to enable the use of Burndown Charts - these look useful for trying to ensure progress happens *linearly*
* [ ] Try labelling by: Goal (of which we have multiple), Criticality, Opportunity ("help wanted") - and move to color scheme that brings these things out. Labels are good for 2 things: filtering the issue list, and improving visual parsing of both the list and the ZenHub board.
* [ ] Clean up the watchlist, by asking old owners if they want to be removed.

**Comment by drphilmarshall** [comment]
Looks like "story points" are just an [abstract measure of task complexity that are defined by agreement among the group](https://www.mountaingoatsoftware.com/blog/the-main-benefit-of-story-points). So, I can go ahead and make estimates for all issues, and everyone else can calibrate the meaning from that. I think. Then, ZenHub will make "burndown charts" for us, [like this](https://www.zenhub.io/blog/burndown-charts-in-github/). 

The ZenHub story point scale runs from 1 to 40, and looks sort of logarithmic. I'll try estimating according to 1 story point = 1 Phil-hour, and see how I get on.

**Comment by drphilmarshall** [comment]
OK, I have done half the issue reorg work:
* Identified epics and labelled them, and their associated issues, accordingly
* New labeling color scheme to try and make it easy to filter issues by epic, and also by pathfinder category.
* Brought all milestones up to date, and ensured all issues are assigned

Next is to implement other labels ("criticality") and then provide links to these filterings on the README page. After that, I'll see about doing some estimates to enable burndown plots.

**Comment by connolly** [comment]
@tony-johnson @drphilmarshall 

Looks like zenhub will now do epics which could make the organization of tasks easier

https://www.zenhub.io/blog/working-with-epics-in-github/

**Comment by drphilmarshall** [comment]
Nice! Looks like they implement the same functionality that our homegrown system has, with the added feature of keeping track of the story points associated with the epic. I'll upgrade each epic issue to a ZenHub epic as I do my rounds. Thanks!

**Comment by cwwalter** [comment]
BTW, currently you can only use this on Chrome.  Here is an issue to make it work with Safari:

https://github.com/ZenHubIO/support/issues/53

**Comment by drphilmarshall** [comment]
@tony-johnson I think you are close to being able to complete the [Run 2 Data Release Milestone](https://github.com/DarkEnergyScienceCollaboration/Twinkles/milestone/13) - would you mind taking a look and seeing if you can close all the issues this week (one way or another), please?

Likewise, @jbkalmbach and @rbiswas4 the [Run 1.1 Analysis milestone](https://github.com/DarkEnergyScienceCollaboration/Twinkles/milestone/18) should be closeable if you both manage to get light curves extracted and analyzed in time for the collaboration meeting! :-)

**Comment by drphilmarshall** [comment]
I'm going to close this, on the grounds that I now understand issues and ZenHub boards and how to use them. The issues will always need tending, but they are in much better shape than when we made this issue.
