### ISSUE TITLE
Twinkles 1 Specifications Document

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#200]
We said we'd write one; we even set ourselves a [deadline](https://github.com/DarkEnergyScienceCollaboration/Twinkles/milestones) of the end of the Oxford collaboration meeting. So, what do we need to do?

* [ ] Decide on the scope of Twinkles 1 #64 
* [ ] Adjust the Science Roadmap accordingly #75 
* [ ] Code up the specifications of the Twinkles 1 project in latex
  * [ ] Format sensibly, based on SRM and CI2 experience e.g. #78 
  * [ ] Survey (cadence, field, rotation, dithering etc)
  * [ ] Image simulation assumptions
  * [ ] DM L2 processing emulation and assumptions 
  * [ ] The meaning of being a "pathfinder"
  * [ ] Infrastructure needed (workflow, framework etc) #77 
* [ ] Internal review by Twinkles Task Force
* [ ] Presentation in Oxford plenary session

Feel free to edit, or add to, this list!

@wmwv @SimonKrughoff @richardxdubois
