### ISSUE TITLE
Upgrade Cookbook to enable instance catalog generation at SLAC

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#243]
So, let's see - what do we need to be able to generate instance catalogs outside UW?

* [x] Generalize the Cookbook into a folder @drphilmarshall #244 
* [ ] Make a Sims Recipe in a Cookbook folder @danielsf #246
* [x] Get set up to run procedures in Sims Recipe at SLAC, and carry out small test @TomGlanzman

**Comment by drphilmarshall** [comment]
Closing this, as it has been superceded by the wondrous new Epic #320.
