### ISSUE TITLE
Sprinkle foreground lensing galaxies based upon match to Catsim mass and redshift

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#310]
Currently all lens galaxies in the sprinkler have the same radius and SED. We will improve upon this by finding CATSIM galaxies within an appropriate range of redshift and mass and taking the CATSIM size and SED to use as input for the sprinkled instance catalogs.

**Comment by jbkalmbach** [comment]
From Scott: "You will need to be careful.  PhoSim (and thus CatSim) specify galaxy size as a semimajor and semiminor axis, so ellipticity is implied."

**Comment by drphilmarshall** [comment]
If we have enough CatSim galaxies to select on ellipticity as well as mass and redshift that would be ideal. The OM10 catalog gives an ellipticity defined as `e = 1 - b/a` where `b` is the semi-minor and `a` the semi-major axis.

From the [CatSim schema](https://confluence.lsstcorp.org/display/SIM/Database+Schema) I'd say we want to match OM10 velocity dispersions based on `mass_stellar`. Is that a total stellar mass (eg associated with a Sersic model), or the mass within some aperture? 

The best way to match OM10 to CatSim is probably to get an empirical resampling in log10(mass_stellar) - vdisp - redshift from @astrosonnen (who has a model constrained by the SL2S and SLACS lens samples, in his [SL2S Paper V](http://arxiv.org/pdf/1410.1881v3.pdf)), and then work with that. That way we can replace the OM10 lens galaxy magnitudes (which I don't really trust) with CatSim galaxy magnitudes. Alessandro, can you help us out please? We just need a set of posterior samples drawn from Pr(logMstar, vdisp, zd | SL2S, SDSS) (ie marginalized over all your other parameters). Do you have this to hand, or could you make it for us quickly, please? Thanks!

**Comment by rbiswas4** [comment]
> From the CatSim schema I'd say we want to match OM10 velocity dispersions based on mass_stellar. Is that a total stellar mass (eg associated with a Sersic model), or the mass within some aperture?

It should be total stellar mass associated with a galaxy (not sure if that is the same as what you mean by associated with a Sersic Model). 

Is there a reason why the velocity dispersion does not depend on the DM mass of the galaxy?

**Comment by drphilmarshall** [comment]
It does, but it correlates more strongly with the stellar mass. We *could*
ask @astrosonnen for halo masses as well, but the existing strong lens data
do not constrain the relation between mass_halo and vdisp as well - so I
think we can keep it simple and just work with mass_stellar.

**Comment by jbkalmbach** [comment]
@drphilmarshall We haven't heard back from @astrosonnen and we're running close to our deadline for the new instance catalog generation routines. Do you have any suggestions on how to proceed?

**Comment by drphilmarshall** [comment]
Let's work with the SL2S sample directly, on the grounds that it should
match up well with the types of lenses we expect from LSST. Table 3 of
Sonnenfeld et al 2013 (Paper IV, page 7) contains a small dataset where z,
M*, vdisp and Reff are all measured. Let's make a quick XD GMM model of
these data, that we can then use to predict M* and Reff given OM10 z and
vdisp. This is a very similar exercise to the one carried out by Tom
Holoien and me for supernovae, in the EmpiriciSN project. I think we can
just copy the notebook from the link below, and adapt it to predict M* and
Reff given the OM10 catalog (which can also be imported to that notebook).
What do you think? Want to have a go at it?

https://github.com/tholoien/empiriciSN/blob/master/Notebooks/Demo.ipynb

Things we'll need to do:
* [ ] Manually scrape out Table 3 into an informatively named and well
formatted `csv` file
* [ ] Install the requirements for empiricisn, notably XDGMM and
dependencies
* [ ] Make an XDGMM model with 1,2,3 etc components, and inspect the BIC
for each
* [ ] Choose a suitable component number and draw replica data, checking
that it matches the input and extends over the domain of z and vdisp that
we are interested in.
* [ ] Condition the GMM on z and vdisp
* [ ] Generate the sample of lenses we want from OM10 and TDC1
* [ ] Step through the lens catalog, drawing an Reff and M* value for each
lens galaxy from the GMM

**Comment by drphilmarshall** [comment]
@jbkalmbach Shall we meet up by Skype at 2pm for an hour to pair code this? I can also do 2:30pm or 3pm, but have to go by 4pm.

**Comment by jbkalmbach** [comment]
Sounds good. See you @ 2.

**Comment by jbkalmbach** [comment]
@drphilmarshall Take a look at our branch for this and let me know if everything looks right. If it does, then I'll go ahead and import our OM10 systems into the notebook and work on them.

**Comment by drphilmarshall** [comment]
I think it's in pretty good shape. Let's continue this discussion in the PR I just started, #334

**Comment by jbkalmbach** [comment]
Closed by merging of #334
